# Generated by Django 2.1.7 on 2019-02-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
